export const SELECT_VIDEOS = 'SELECT_VIDEOS';
export const UPDATE_VIDEOS_LIST = 'UPDATE_VIDEOS_LIST';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';

export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
